<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3912.50" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260308" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260302" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.13.0.20260308" />
    <PackageReference Include="System.IO.Ports" Version="10.0.3" />
    <PackageReference Include="System.Net.Sockets" Version="4.3.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23" />
    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Masaüstü\HUD-master\HUD\HUD.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="map.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
